# Data Configuration
data:
  data_path: "data/CreditCardData.csv"  # Path to raw data
  processed_dir: "data/processed"  # Directory for processed data
  target_column: "Fraud"  # Name of the target column

# Preprocessing Configuration
preprocessing:
  random_state: 42  # Random seed for reproducibility
  test_size: 0.2
  validation_size: 0.2
  smote_ratio: 0.5  # Minority class will be increased to 50% of majority
  undersampling_ratio: 0.8  # Keep 80% of majority class
  
  # Feature Engineering
  time_features:
    enabled: true
    features: ["hour", "day_of_week", "is_weekend"]
  
  amount_features:
    enabled: true
    features: ["amount_log", "amount_bins"]
  
  # Missing Value Strategy
  missing_values:
    numerical: "median"
    categorical: "mode"
  
  # Outlier Treatment
  outliers:
    method: "iqr"  # Options: iqr, zscore
    threshold: 1.5  # IQR multiplier or z-score threshold

# Model Configuration
model:
  # Model type: 'mlp', 'cnn', 'lstm', 'random_forest', 'xgboost', 'lightgbm'
  type: "lstm"
  
  # Deep Learning Model (MLP) Configuration
  mlp:
    hidden_dims: [128, 64, 32]  # Hidden layer dimensions
    dropout_rate: 0.3
  
  # Convolutional Neural Network (CNN) Configuration
  cnn:
    num_filters: [64, 128, 64]  # Number of filters for each conv layer
    kernel_sizes: [3, 3, 3]     # Kernel sizes for each conv layer
    hidden_dims: [128, 64]      # Hidden layer dimensions for FC layers
    dropout_rate: 0.3
  
  # Long Short-Term Memory (LSTM) Configuration
  lstm:
    lstm_hidden_dims: [128, 64]  # Hidden dimensions for LSTM layers
    num_layers: [2, 2]           # Number of layers for each LSTM stack
    hidden_dims: [128, 64]       # Hidden layer dimensions for FC layers
    dropout_rate: 0.3
    bidirectional: true          # Use bidirectional LSTM
  
  # Models already have good defaults in their factory classes

# Training Configuration
training:
  batch_size: 64
  
  # Cross-validation settings
  cv:
    n_splits: 5
    shuffle: true
    random_state: 42
  
  # Early stopping settings
  early_stopping:
    monitor: "val_loss"  # Metric to monitor: val_loss, val_auc
    patience: 5  # Number of epochs to wait before stopping
    min_delta: 0.001  # Minimum change to qualify as an improvement
    
  # Model selection criteria
  model_selection:
    metric: "f1"  # Metric to use for model selection
    greater_is_better: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/fraud_detection.log"

# Evaluation Configuration
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
  threshold_optimization:
    method: "f1"  # Metric to optimize threshold: f1, precision, recall
    n_thresholds: 100  # Number of thresholds to evaluate

# Inference Configuration
inference:
  test_file: "data/test.csv"  # Path to test data for inference
  threshold: 0.5  # Default threshold for binary classification
  output_dir: "predictions" 